# See https://pre-commit.com/ for usage and config
default_language_version:
  python: python3.12
fail_fast: true
repos:
- repo: local
  hooks:
  - id: black
    name: black
    stages: [ pre-push ]
    language: system
    types:
      - python
    entry: make black
    pass_filenames: false

  - id: ruff
    name: ruff
    stages: [ pre-push ]
    language: system
    types:
      - python
    entry: make ruff
    pass_filenames: false

  - id: mypy
    name: mypy
    stages: [ pre-push ]
    language: system
    types:
      - python
    entry: make mypy
    pass_filenames: false